include:
  package:
    flutter_lints/flutter.yaml
    very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    inference_failure_on_function_invocation: ignore
  language:
    # strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    require_trailing_commas: true
    always_declare_return_types: true
    use_super_parameters: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    unawaited_futures: true
    avoid_catching_errors: true
    avoid_positional_boolean_parameters: true
    avoid_field_initializers_in_const_classes: true
    flutter_style_todos: true
    matching_super_parameters: true
    leading_newlines_in_multiline_strings: true
    sort_pub_dependencies: true
    unnecessary_breaks: true
    unnecessary_raw_strings: true
    unnecessary_underscores: true
    use_named_constants: true
    use_to_and_as_if_applicable: true
    #avoid_dynamic_calls: true
    no_runtimeType_toString: true
    omit_obvious_local_variable_types: true
    #omit_obvious_property_types: true
    only_throw_errors: true
    prefer_void_to_null: true
    use_enums: true
    avoid_slow_async_io: true
    avoid_void_async: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    do_not_use_environment: true
    prefer_int_literals: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    throw_in_finally: true
    use_colored_box: true
    use_decorated_box: true
    use_truncating_division: true

dcm:
  exclude:
    rules:
      - "test/**" 
  rules:
    - always-remove-listener
    #- avoid-border-all
    - avoid-expanded-as-spacer
    - avoid-incomplete-copy-with
    - avoid-incorrect-image-opacity
    #- avoid-missing-image-alt
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-unnecessary-stateful-widgets
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    #- prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    #- prefer-define-hero-tag
    #- prefer-extracting-callbacks
    - prefer-single-widget-per-file
    - prefer-text-rich
    #- prefer-using-list-view
    - use-setstate-synchronously
    - avoid-assignments-as-conditions
    - avoid-cascade-after-if-null
    - avoid-casting-to-extension-type
    - avoid-collection-methods-with-unrelated-types
    - avoid-commented-out-code
    - avoid-conditions-with-boolean-literals
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-duplicate-mixins
    - avoid-duplicate-named-imports
    - avoid-duplicate-test-assertions
    #- avoid-dynamic
    - avoid-empty-spread
    - avoid-explicit-pattern-field-name
    - avoid-generics-shadowing
    #- avoid-global-state
    - avoid-late-keyword
    - avoid-missed-calls
    - avoid-misused-set-literals
    #- avoid-nested-conditional-expressions
    - avoid-nested-records
    #- avoid-non-null-assertion
    - avoid-nullable-tostring
    - avoid-passing-async-when-sync-expected
    - avoid-passing-self-as-argument
    - avoid-redundant-async
    - avoid-self-assignment
    - avoid-self-compare
    - avoid-substring
    - avoid-throw-in-catch-block
    #- avoid-top-level-members-in-tests
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering
    - missing-test-assertion
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    #- no-magic-number
    - prefer-async-await
    #- prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-test-file-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    #- prefer-match-file-name
    #- prefer-moving-to-variable
    - prefer-static-class
    