org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Let JVM/Gradle reuse Windows proxy (PAC/manual) settings.
systemProp.java.net.useSystemProxies=true
# Prefer IPv4 in restrictive corporate networks.
systemProp.java.net.preferIPv4Stack=true
